apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec: 
  type: NodePort
  ports: 
    - port: 80
      nodePort: 30000  #30000-32767 #porta que será exposta para o mundo externo
  selector: 
    app: primeiro-pod